//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 08. 16:42:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace masterModel
{
    public partial class Megnézendő_film {

        public Megnézendő_film()
        {
            this.Filmek = new List<Film>();
            OnCreated();
        }

        public int lista_id { get; set; }

        public string film_id { get; set; }

        public DateTime hozzáadási_dátum { get; set; }

        public virtual IList<Film> Filmek { get; set; }

        public virtual Lisa Lisa { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
