//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 08. 16:42:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace masterModel
{
    public partial class Film {

        public Film()
        {
            this.Értékelés = new List<Értékelés>();
            this.Megnézendő_film = new List<Megnézendő_film>();
            OnCreated();
        }

        public int film_id { get; set; }

        public int Időtartam { get; set; }

        public int Megjelenési_év { get; set; }

        public double Átlag_értékelés { get; set; }

        public string Kép { get; set; }

        public string Műfaj { get; set; }

        public string Cím { get; set; }

        public virtual IList<Értékelés> Értékelés { get; set; }

        public virtual IList<Megnézendő_film> Megnézendő_film { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
