//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 08. 16:42:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace masterModel
{
    public partial class Értékelés {

        public Értékelés()
        {
            OnCreated();
        }

        public int értékelés_id { get; set; }

        public int csillagok { get; set; }

        public DateTime közlési_dátum { get; set; }

        public string tartalom { get; set; }

        public int film_id { get; set; }

        public int felhasználó_id { get; set; }

        public virtual Film Film { get; set; }

        public virtual Felhasználó értékelések { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
