//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 08. 16:42:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace masterModel
{
    public partial class Felhasználó {

        public Felhasználó()
        {
            this.Értékelés = new List<Értékelés>();
            this.Lisas = new List<Lisa>();
            OnCreated();
        }

        public int felhasználó_id { get; set; }

        public string Felhasználó_név { get; set; }

        public string jelszó { get; set; }

        public string email { get; set; }

        public virtual IList<Értékelés> Értékelés { get; set; }

        public virtual IList<Lisa> Lisas { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
