//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 08. 16:42:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace masterModel
{
    public partial class Lisa {

        public Lisa()
        {
            this.Megnézendő_filmek = new List<Megnézendő_film>();
            OnCreated();
        }

        public int lista_id { get; set; }

        public string név { get; set; }

        public int Felhasználó_id { get; set; }

        public virtual Felhasználó felhasználólista { get; set; }

        public virtual IList<Megnézendő_film> Megnézendő_filmek { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
